### ISSUE TITLE
link to bert example is broken

### ISSUE THREAD

**Issue by Sandy4321** [mosaicml/examples#347]
link to bert example is broken from 
https://huggingface.co/mosaicml/mosaic-bert-base
and
https://www.mosaicml.com/blog/mosaicbert

https://github.com/mosaicml/examples/tree/main/examples/bert#single-task-fine-tuning
https://github.com/mosaicml/examples/tree/main/examples/bert

![image](https://github.com/mosaicml/examples/assets/11426119/970c10b2-e0c4-4da6-bc93-813888bdd42c)

and

![image](https://github.com/mosaicml/examples/assets/11426119/8a7fc1ea-968f-49fa-af8d-11daccc24413)

**Comment by mvpatel2000** [comment]
Thanks for flagging this! We're restructuring our examples repo, and the path changed. We will update the docs soon. Here is the link to unblock you for now: https://github.com/mosaicml/examples/tree/main/examples/benchmarks/bert

**Comment by jacobfulano** [comment]
The HF README for [mosaic-bert-base](https://huggingface.co/mosaicml/mosaic-bert-base) has been updated, and we will update the blogpost. Thank you for flagging this
