### ISSUE TITLE
will fine tuning  work on windows 11 lap top minimal gpu for bert sequence_classification.py ?

### ISSUE THREAD

**Issue by Sandy4321** [mosaicml/examples#348]
https://github.com/mosaicml/examples/blob/main/examples/benchmarks/bert/sequence_classification.py

will fine tuning  work on windows 11 lap top minimal gpu ?
print(torch.cuda.get_device_name(0))
NVIDIA GeForce RTX 3050 Ti Laptop GPU

**Comment by mvpatel2000** [comment]
I believe it should work since its an NVIDIA GPU. We haven't tested it, so please let us know if you hit any issues. Happy to help!

I'm going to close for now, but feel free to reopen if you hit issues

**Comment by Sandy4321** [comment]
sure 
what is link to code example to try for text binary classificatoin ?

**Comment by mvpatel2000** [comment]
Take a look at the BERT examples: https://github.com/mosaicml/examples/tree/main/examples/benchmarks/bert

**Comment by Sandy4321** [comment]
great thanks for soon answer
then what munimal computing I Need for classification for fine tuning  IMDB data set?
1 is it enouth CPU only laptop 32 GB RAM?
2 will it run on free google colab tier  ?
2 will it run on free AWS sagemaker lab  ?

**Comment by mvpatel2000** [comment]
Unfortunately, we don't have those kind of details on hand. I recommend trying it and seeing what happens!
